language: ruby

before_install:
  - gem update --system
  - gem install bundler

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml

script:
 - bundle exec rake db:migrate
 - bundle exec rspec